kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: amarburg/drone-ci-melodic-ros-base
  commands:
    - apt update && apt install -y libavdevice-dev
    - wget -O- https://gitlab.com/amarburg/ros_drone_ci/-/raw/master/bootstrap.sh | /bin/bash
  environment:
    ROS_PACKAGES_TO_INSTALL: cv-bridge image-transport opencv-apps
    WSTOOL_RECURSIVE: true
