kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: amarburg/drone-ci-melodic-ros-base
  shell: /bin/bash
  commands:
    - wget -O- https://gitlab.com/amarburg/ros_drone_ci/-/raw/master/bootstrap.sh | /bin/bash
