name: Bidirectional GitHub ↔ GitLab Sync

on:
  workflow_dispatch:         # Manual run via GitHub UI
  schedule:
    - cron: '0 * * * *'       # Run hourly

permissions:
  contents: write             # Required to push to GitHub

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git identity
      run: |
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

    - name: Clone GitHub repository (bare)
      run: |
        git clone --bare "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" /tmp/repo.git

    - name: Add GitLab remote and fetch
      run: |
        cd /tmp/repo.git
        git remote remove gitlab || true
        git remote add gitlab "${{ secrets.GITLAB_REPO_URL }}"
        git fetch --all

    - name: Pull from GitLab and push to GitHub
      run: |
        cd /tmp/repo.git
        for branch in $(git for-each-ref --format='%(refname:short)' refs/remotes/gitlab/); do
          name=$(echo "$branch" | sed 's|^gitlab/||')
          git branch -f "$name" "gitlab/$name" || true
        done
        git push origin --all
        git push origin --tags

    - name: Pull from GitHub and push to GitLab
      run: |
        cd /tmp/repo.git
        for branch in $(git for-each-ref --format='%(refname:short)' refs/remotes/origin/); do
          name=$(echo "$branch" | sed 's|^origin/||')
          git branch -f "$name" "origin/$name" || true
        done
        git push gitlab --all
        git push gitlab --tags
