name: Bidirectional GitHub ↔ GitLab Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # every hour

jobs:
  bidirectional-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

    - name: Clone GitHub repository (bare)
      run: |
        git clone --bare "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" repo.git


    - name: Add GitLab remote and fetch
      run: |
        cd repo.git
        git remote add gitlab "${{ secrets.GITLAB_REPO_URL }}"
        git fetch gitlab

    - name: Pull from GitLab and push to GitHub
      run: |
        cd repo.git
        for branch in $(git for-each-ref --format='%(refname:short)' refs/remotes/gitlab/); do
          git branch -f "$branch" "gitlab/$branch" || true
        done
        git push origin --all
        git push origin --tags

    - name: Pull from GitHub and push to GitLab
      run: |
        cd repo.git
        for branch in $(git for-each-ref --format='%(refname:short)' refs/remotes/origin/); do
          git branch -f "$branch" "origin/$branch" || true
        done
        git push gitlab --all
        git push gitlab --tags
